colunms:
  id: int64
  log_price: float64
  property_type: object
  room_type: object
  amenities: object
  accommodates: int64
  bathrooms: float64
  bed_type: object
  cancellation_policy: object
  cleaning_fee: bool
  city: object
  description: object
  first_review: object
  host_has_profile_pic: object
  host_identity_verified: object
  host_response_rate: object
  host_since: object
  instant_bookable: object
  last_review: object
  latitude: float64
  longitude: float64
  name: object
  neighbourhood: object
  number_of_reviews: int64
  review_scores_rating: float64
  thumbnail_url: object
  zipcode: object
  bedrooms: float64
  beds: float64
